/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include <iostream>
#include <conio.h>
#include <vector>
#include <string>
#include <boost/algorithm/string/split.hpp>
#include <boost/algorithm/string/classification.hpp>
#include <cstdlib>
#include <ctime>
#include <sstream>
using namespace std;
/* Header for class TicTacToeApp */

#ifndef _Included_TicTacToeApp
#define _Included_TicTacToeApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TicTacToeApp
 * Method:    Random
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TicTacToeApp_Random
  (JNIEnv *, jobject, jstring tab);

/*
 * Class:     TicTacToeApp
 * Method:    MyAlg
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TicTacToeApp_MyAlg
  (JNIEnv *, jobject, jstring tab);

bool wygrana(string t[4][4], string  g);
#ifdef __cplusplus
}
#endif
#endif
